#!/bin/bash
# openoffice headless server script
#
OOO_HOME=/Applications/office/OpenOffice.org.app/Contents
PIDFILE=$OOO_HOME/openoffice-headless.pid
LOGFILE=$OOO_HOME/openoffice-headless.log

case "$1" in
start)
if [ -f $PIDFILE ] ; then
ps -ef | grep -i soffice | grep -v grep > /dev/null
if [ $? -eq 0 ] ; then
echo "OpenOffice headless is already running pid $(cat $PIDFILE)."
exit
fi
fi
echo "Starting OpenOffice headless server..."
cd $OOO_HOME/program
./soffice.bin -headless -accept="socket,port=8100;urp;" & > $LOGFILE 2>&1
echo $! | tee $PIDFILE
;;

stop)
if [ -f $PIDFILE ] ; then
echo "Stopping OpenOffice headless server..."
killall -9 soffice.bin
rm -f $PIDFILE
exit 0
fi
echo "No openoffice to stop."
;;

status)
if [ -f $PIDFILE ] ; then
echo "OpenOffice headless running pid $(cat $PIDFILE)."
else
echo "No pid file $PIDFILE"
fi
echo "Processes named soffice:"
ps | grep -i soffice | grep -v grep
;;

*)
echo "Usage: $0 {start|stop|status}"
exit 1
esac

exit 0