#!/bin/bash
# openoffice headless server script
#
OOO_HOME=/Applications/office/OpenOffice.org.app/Contents
THIS_PATH=`pwd`
PIDFILE=$THIS_PATH/tmp/pids/openoffice-headless.pid
LOGFILE=$THIS_PATH/log/openoffice-headless.log

case "$1" in
start)
if [ -f $PIDFILE ] ; then
ps -A | grep -i soffice | grep -v grep > /dev/null
if [ $? -eq 0 ] ; then
echo "OpenOffice headless is already running pid $(cat $PIDFILE)."
exit
fi
fi
echo "Starting OpenOffice headless server..."

# Change directory, needed on OSX
cd $OOO_HOME/program
./soffice.bin -headless -nofirststartwizard -accept="socket,host=localhost,port=8100;urp;StarOffice.Service" & > $LOGFILE 2>&1
echo $! | tee $PIDFILE
;;

stop)
if [ -f $PIDFILE ] ; then
echo "Stopping OpenOffice headless server..."
killall -9 soffice.bin
rm -f $PIDFILE
exit 0
fi
echo "No openoffice to stop."
;;

status)
echo "Processes named soffice:"
ps -A | grep -i soffice | grep -v grep
if [ -f $PIDFILE ] ; then
echo "OpenOffice headless running pid $(cat $PIDFILE)."
else
echo "No pid file $PIDFILE"
exit 1
fi
;;

*)
echo "Usage: $0 {start|stop|status}"
exit 1
esac

exit 0